### ISSUE TITLE
run "python refresh.py" failed

### ISSUE THREAD

**Issue by luckypoem** [olivierthereaux/otCMS#1]
hi.
root@as3:~/otcms/bin# ls
makegall.py  rdfize.py  refresh.py  thumb
root@as3:~/otcms/bin# python refresh.py
Traceback (most recent call last):
  File "refresh.py", line 394, in <module>
    sys.exit(main())
  File "refresh.py", line 75, in main
    entries, path = otCMS.loadcatalog(private=private)
  File "../lib/otCMS.py", line 157, in loadcatalog
    exec(open(catalog,"rb").read())
IOError: [Errno 2] No such file or directory: '../lib/~/otcms/samples/catalog.py'
root@as3:~/otcms/bin#

how to fix the error?tks

**Comment by olivierthereaux** [comment]
Hello,

I suspect you set up your catalog path to "~/otcms/samples/catalog.py" in your settings.py. Try setting the full path (/home/username/otCMS/samples/catalog.py) or a path relative to lib (../samples/catalog.py) rather than the path with ~, which python OS library doesn't seem to understand.

**Comment by olivierthereaux** [comment]
The latest version of refresh.py fixes this by:
- looking for the file "catalog.py" (or "private.py") in a number of potential location
- giving the user the ability to specify the location if the catalog file can not be found automatically

**Comment by luckypoem** [comment]
hi.

root@AR:/usr/local/otCMS# bin/refresh.py --catalog ./samples/ --htdocs output

refresh.py - regenerate entries and indexes

Usage: refresh.py [Options]

Optional

Options:
    --catalog   set path for entries catalog.
                By default, will look for "catalog.py" in current directory
      ... or "private.py" if option "-p" is set (see below)
    --htdocs    set path for where the entries should be generated
                By default, will consider path of catalog file to be the root
    -p          use  private catalog.
                Will only generate entries, no indexes
    -h (--help) This help message

root@AR:/usr/local/otCMS# ls
bin  lib  README.md  samples  templates
root@AR:/usr/local/otCMS#

in the readme, u said:"Connect with your htdocs directory by setting the right parameters in config/settings.py",but i didn't see config dir nor settings.py,where are they??

tks

**Comment by luckypoem** [comment]
root@AR:/usr/local/otCMS# find . -name settings.py
root@AR:/usr/local/otCMS#

and can u publish ur site's repo in github.com?

**Comment by olivierthereaux** [comment]
@luckypoem I need to update the readme - the update I made a few days ago removes the settings.py config file in favour of --htdocs and --catalog. 

In the example you give:
`--catalog ./samples/`
is not what the script expects. Try instead something like:
`--catalog ./samples/catalog.py`

Also note the slight change of syntax in the catalog since the last update.

**Comment by luckypoem** [comment]
HI.

root@AR:/usr/local/otCMS# bin/refresh.py --catalog ./samples/catalog.py
Catalog read successfully. 3 entries loaded
Writing files with /usr/local/otCMS as htdocs root directory
/usr/local/lib/python2.7/dist-packages/pygments/plugin.py:39: UserWarning: Module pygments was already imported from /usr/local/lib/python2.7/dist-packages/pygments/__init__.pyc, but /usr/local/lib/python2.7/dist-packages/Pygments-2.1.3-py2.7.egg is being added to sys.path
  import pkg_resources
Traceback (most recent call last):
  File "bin/refresh.py", line 531, in <module>
    sys.exit(main())
  File "bin/refresh.py", line 160, in main
    yearly_lang_selection[entry.language][entry.year].append(entry)
KeyError: None
root@AR:/usr/local/otCMS#

HOW TO FIX THE ERROR?
THANK YOU.

**Comment by olivierthereaux** [comment]
Hi @luckypoem - looks like an issue I have not encountered before, possibly because you have not filled the "year" info for some of your entries. Is there any chance you could share your catalog with me?

**Comment by luckypoem** [comment]
hi.

it's just ur catalog.py:

root@AR:/usr/local/otCMS/samples# cat catalog.py
# Your entries. Add newer ones at the top.
[

    {
        "URI": "/2013/01-Foo-bar/",
        "Title": u"""Foo Bar""",
        "Pubdate": "2013-01-07T21:42:42Z",
        "Year":  2013
    },
    {
        "URI": "/2012/12-Lorem/",
        "Title": u"""Lorém IPSUM""",
        "Pubdate": "2012-12-30T23:42:42Z",
        "Thumbnail": "/2012/12-Lorem/foobar.png",
        "Abstract": u"""Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna """,
        "Photos":  12 ,
        "Year":  2012 ,
        "Continent":  "Europe" ,
        "Country":  "Spain" ,
        "City":  "Barcelona" ,
    },
    {
        "URI": "/2012/11-London-Manchester/",
        "Title": u"""""",
        "Pubdate": "2012-12-30T21:42:42Z",
        "Thumbnail": "http://example.com/images/foo.jpg",
        "Abstract": u"""Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.""",
        "Photos":  8,
        "Year":  2012 ,
        "Continent":  "Europe" ,
        "Country":  "UK" ,
        "City":  ["London" , "Manchester"]
    },
]
root@AR:/usr/local/otCMS/samples#

**Comment by luckypoem** [comment]
how to write the source post?can u give me a demo of source post?
